MVC/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class Company
    {
        [Key]
        public string Code { get; set; }
        public string Name { get; set; }
        public string Group { get; set; }
    }
}

MVC/Models/CompanyContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class CompanyContext : DbContext
    {
        public DbSet<Company> Companies { get; set; }
        public DbSet<IndustryGroup> IndustryGroups { get; set; }
    }
}

MVC/Models/IndustryGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    // The following attribute is required if the table name is other than IndustryGroups (the plural form of the class name)
    // [Table("IndustryGroups")]
    public class IndustryGroup
    {
        [Key]
        public string Group { get; set; }
        public List<Company> Companies { get; set; }
    }
}

MVC/Models/Property.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class Property
    {
        [Key, Column(Order = 1)]
        public string Street { get; set; }
        [Key, Column(Order = 2)]
        public string Number { get; set; }
        [Key, Column(Order = 3)]
        public string Suburb { get; set; }
        [Key, Column(Order = 4)]
        public string State { get; set; }
        [Key, Column(Order = 5)]
        public string Postcode { get; set; }
        public byte Type { get; set; }
        public decimal Price { get; set; }
        public DateTime SoldDate { get; set; }
    }
}

MVC/Models/PropertyContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class PropertyContext : DbContext
    {
        public DbSet<Property> Properties { get; set; }
    }
}

MVC/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;

namespace MVCDemo.Controllers
{
    public class CompanyController : Controller
    {
        /// <summary>
        /// To display this page type in http://localhost/MVC/Company/List?group=Group
        /// </summary>
        public ActionResult List(string group)
        {
            var companyContext = new CompanyContext();
            var companies = companyContext.Companies.Where(c => c.Group == group).ToList();
            return View(companies);
        }

        /// <summary>
        /// To display this page type in http://localhost/MVC/Company/Details?code=CompanyCode
        /// </summary>
        public ActionResult Details(string code)
        {
            var companyContext = new CompanyContext();
            var company = companyContext.Companies.Single(c => c.Code == code);
            return View(company);
        }
    }
}

MVC/Controllers/FamilyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.Controllers
{
    public class FamilyController : Controller
    {
        /// <summary>
        /// To display this page type in http://localhost/MVC/Family/Members
        /// </summary>
        public ActionResult Members()
        {
            ViewBag.Members =
                new List<string>
                {
                    "Herman",
                    "Helen",
                    "Sarah",
                    "Olivia"
                };
            return View();
        }
    }
}

MVC/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;

namespace MVCDemo.Controllers
{
    public class GroupController : Controller
    {
        /// <summary>
        /// To display this page type in http://localhost/MVC/Group/List
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            var companyContext = new CompanyContext();
            var groups = companyContext.IndustryGroups.ToList();
            return View(groups);
        }
    }
}

MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// To display this page type in http://localhost/MVC/Home/Default/xx?querystr1=yy&querystr2=zz
        /// where id, querystr1 and querystr2 are optional
        /// </summary>
        public string Default(string id, string querystr1, string querystr2)
        {
            var output = "Hello World!";
            if (!String.IsNullOrEmpty(id))
            {
                output = String.Format("Id - {0}", id);
                if (!String.IsNullOrEmpty(querystr1))
                {
                    output = String.Format("{0} - {1}", output, querystr1);
                    if (!String.IsNullOrEmpty(querystr2))
                    {
                        output = String.Format("{0} - {1}", output, querystr2);
                    }
                }
            }
            return output;
        }
    }
}

MVC/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;

namespace MVCDemo.Controllers
{
    [System.Runtime.InteropServices.GuidAttribute("B27E542D-848B-4650-B8CD-A396B31919F7")]
    public class PropertyController : Controller
    {
        /// <summary>
        /// To display this page type in http://localhost/MVC/Property/List
        /// </summary>
        public ActionResult List()
        {
            var propertyContext = new PropertyContext();
            var properties = propertyContext.Properties.ToList();

            return View(properties);
        }

        /// <summary>
        /// To display this page type in http://localhost/MVC/Property/Create
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Property property)
        {
            if (ModelState.IsValid)
            {
                var propertyContext = new PropertyContext();
                propertyContext.Properties.Add(property);
                propertyContext.SaveChanges();
                return RedirectToAction("List");
            }
            return View();
        }

        /// <summary>
        /// To display this page type in http://localhost/MVC/Property/Edit?number=8&street=Abbey%20Place&suburb=Cherrybrook&state=NSW&postcode=2126
        /// </summary>
        [HttpGet]
        public ActionResult Edit(string number, string street, string suburb, string state, string postcode)
        {
            var propertyContext = new PropertyContext();
            var property = propertyContext.Properties.Single(p => p.Number == number && p.Street == street && p.Suburb == suburb);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        [HttpPost]
        public ActionResult Edit(Property property)
        {
            if (ModelState.IsValid)
            {
                var propertyContext = new PropertyContext();
                propertyContext.Properties.Add(property);
                propertyContext.SaveChanges();
                return RedirectToAction("List");
            }
            return View();
        }
    }
}

MVC/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.Controllers
{
    public class TestController : Controller
    {
        public ActionResult Test()
        {
            return View();
        }
    }
}

MVC/Views/Company/Details.cshtml
@using MVCDemo.Models

@model Company

@{
    ViewBag.Title = "Company Details";
}

<div style="font-family:Arial">
    <h2>Company Details</h2>
    <table>
        <tr>
            <td><b>Code:</b></td>
            <td>@Model.Code</td>
        </tr>
        <tr>
            <td><b>Name:</b></td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td><b>Group:</b></td>
            <td>@Model.Group</td>
        </tr>
    </table>
    <br/>
    @Html.ActionLink("Back to Company List", "List", new { group = @Model.Group })
</div>

MVC/Views/Company/List.cshtml
@using MVCDemo.Models;

@model IEnumerable<Company>

@{
    ViewBag.Title = "Company List";
}

<div style="font-family:Arial">
    <h2>Company List</h2>
    <ul>
        @foreach (var company in @Model)
        {
            <li>
                @Html.ActionLink(company.Code, "Details", new { code = company.Code })
            </li>
        }
    </ul>
    @Html.ActionLink("Back to Group List", "List", "Group")
</div>

MVC/Views/Family/Members.cshtml
@{
    ViewBag.Title = "Family Members";
}

<div style="font-family:Arial">
    <h2>Family Members:</h2>
    <ul>
        @foreach (var member in ViewBag.Members)
        {
            <li>
                @member
            </li>
        }
    </ul>
</div>

MVC/Views/Group/List.cshtml
@using MVCDemo.Models

@model IEnumerable<IndustryGroup>

@{
    ViewBag.Title = "Group List";
}

<div style="font-family:Arial">
    <h2>Group List</h2>
    <ul>
        @foreach (var group in @Model)
        {
            <li>
                @Html.ActionLink(group.Group, "List", "Company", new { group = group.Group}, null)
            </li>
        }
    </ul>
</div>

MVC/Views/Property/Create.cshtml
@model MVCDemo.Models.Property

@{
    ViewBag.Title = "Create";
}

<div style="font-family:Arial">
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Property</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Number)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Street)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Street)
                @Html.ValidationMessageFor(model => model.Street)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Suburb)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Suburb)
                @Html.ValidationMessageFor(model => model.Suburb)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.State)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Price)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.SoldDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SoldDate)
                @Html.ValidationMessageFor(model => model.SoldDate)
            </div>

            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Back to Property List", "List")
    </div>
</div>

MVC/Views/Property/Edit.cshtml
@model MVCDemo.Models.Property

@{
    ViewBag.Title = "Edit";
}

<div style="font-family:Arial">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Property</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Number)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Street)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Street)
                @Html.ValidationMessageFor(model => model.Street)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Suburb)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Suburb)
                @Html.ValidationMessageFor(model => model.Suburb)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.State)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Postcode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Postcode)
                @Html.ValidationMessageFor(model => model.Postcode)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Price)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.SoldDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SoldDate)
                @Html.ValidationMessageFor(model => model.SoldDate)
            </div>

            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Back to Property List", "List")
    </div>
</div>

MVC/Views/Property/List.cshtml
@using MVCDemo.Models;

@model IEnumerable<Property>

@{
    ViewBag.Title = "Property List";
}

<div style="font-family:Arial">
    <h2>Property List</h2>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Suburb)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoldDate)
            </th>
            <th>
                Action
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Street)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Suburb)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoldDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { number = item.Number, street = item.Street, suburb = item.Suburb, state = item.State, postcode = item.Postcode }) |
                    @Html.ActionLink("Details", "Details", new { number = item.Number, street = item.Street, suburb = item.Suburb, state = item.State, postcode = item.Postcode }) |
                    @Html.ActionLink("Delete", "Delete", new { number = item.Number, street = item.Street, suburb = item.Suburb, state = item.State, postcode = item.Postcode })
                </td>
            </tr>
        }
    </table>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/Views/Test/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

@{var str = "61060";}
@{var val = str.AsInt(123);}
<p>The value is @val</p>

@{var price = 60;}
@if (price > 50)
{
    <p>The price is too high</p>
}
else
{
    <p>The price is okay</p>
}

@{
    var result=0;
    for (int i = 0; i < 6; i++)
    {
        result = result + i;        
    }
}
<h3>The result is = @result</h3>